apiVersion: batch/v1
kind: Job
metadata:
 name: bln600-ocr-correct-job
 labels:
  kueue.x-k8s.io/queue-name: namespace-user-queue
spec:
 completions: 1
 parallelism: 1
 template:
  spec:
   restartPolicy: Never
   containers:
   - name: transformers-quantization-latest-gpu
     image: huggingface/transformers-quantization-latest-gpu
     command: ['sh', '-c', "python3 /code/OCRPostCorrection/corrections/k8s_jobs//bln600_correction.py hf_token"]
     resources:
      requests:
       cpu: 10
       memory: "40Gi"
      limits:
       cpu: 10
       memory: "80Gi"
       nvidia.com/gpu: 1
     volumeMounts:
     - mountPath: /mnt/ceph_rbd
       name: dataset
     - mountPath: /code
       name: github-code
   initContainers:
   - name: lightweight-git-container
     image: cicirello/alpine-plus-plus
     command: ['sh', '-c', "cd /code; git clone https://github.com/frances-ai/OCRPostCorrection.git"]
     resources:
      requests:
       cpu: 1
       memory: "2Gi"
      limits:
       cpu: 1
       memory: "4Gi"
     volumeMounts:
     - mountPath: /code
       name: github-code
   volumes:
   - name: dataset
     persistentVolumeClaim:
      claimName: dataset-pvc
   - name: github-code
     emptyDir:
      sizeLimit: 1Gi

