apiVersion: batch/v1
kind: Job
metadata:
    name: eb-sample-download-job
    labels:
        kueue.x-k8s.io/queue-name:  namespace-user-queue
spec:
    completions: 1
    template:
        metadata:
            name: eb-sample-download-pod
        spec:
            containers:
            - name: data-loader
              image: alpine/curl:latest
              command: ['sh', '-c']
              args:
                - |
                  cd /mnt/ceph_rbd; 
                  rm eb_samples.json;
                  curl https://storage.googleapis.com/damon_public_files/dataframes/eb_samples.json -o eb_samples.json
              resources:
                    requests:
                        cpu: 1
                        memory: '1Gi'
                    limits:
                        cpu: 1
                        memory: '1Gi'
              volumeMounts:
                    - mountPath: /mnt/ceph_rbd
                      name: volume
            restartPolicy: Never
            volumes:
                - name: volume
                  persistentVolumeClaim:
                    claimName: dataset-pvc